# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [53]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001, size=[1000,20])

# print the shape of X
print(X.shape)
print(X)
print(X[1])

(1000, 20)
[[3202 4480  685 ... 1368  380   59]
 [4331 1611 1516 ...  606  971  401]
 [1549 1777  676 ... 1155 2749 4676]
 ...
 [1776 4134 1187 ... 1980  247 3885]
 [3390 1314 4679 ... 3802 4326  879]
 [1384 2635 4840 ... 2781 4269 4605]]
[4331 1611 1516 3965 2333 4839  507 1891 4123 2693  509 1735 1332 2596
 1896 2618 4387  606  971  401]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [113]:
# Average of the values in each column of X
ave_cols = X.mean(axis=0)
print(ave_cols)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis = 0)
print(std_cols)

[2490.114 2487.737 2454.963 2467.57  2491.399 2483.812 2538.675 2496.572
 2507.797 2462.663 2610.714 2453.892 2431.447 2550.711 2498.449 2591.265
 2510.828 2537.845 2449.891 2513.255]
[1460.28299552 1434.89633905 1449.00599779 1411.09675044 1441.34951896
 1414.3937891  1410.69505612 1449.88458189 1434.90346846 1468.14746379
 1470.73989346 1451.89630082 1443.49147389 1470.23589858 1422.25619753
 1452.89631384 1421.47346666 1437.48861873 1467.44934465 1432.7845979 ]
[[3202 4480  685 ... 1368  380   59]
 [4331 1611 1516 ...  606  971  401]
 [1549 1777  676 ... 1155 2749 4676]
 ...
 [1776 4134 1187 ... 1980  247 3885]
 [3390 1314 4679 ... 3802 4326  879]
 [1384 2635 4840 ... 2781 4269 4605]]


If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [55]:
# Print the shape of ave_cols
print(ave_cols.shape)

# Print the shape of std_cols
print(std_cols.shape)


(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [59]:
# Mean normalize X
X_norm = (X - ave_cols) / std_cols
print(X_norm[1])

[ 1.26063647 -0.61101069 -0.64800491  1.06118167 -0.10989631  1.6651572
 -1.44019431 -0.41766911  1.12565273  0.15688955 -1.42901815 -0.49514005
 -0.76165812  0.0308039  -0.42358683  0.01840118  1.31987831 -1.34390281
 -1.00779697 -1.47423067]


If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [116]:
# Print the average of all the values of X_norm
print(X_norm.mean())

# Print the average of the minimum value in each column of X_norm
print(X_norm.min(axis = 0).mean())

# Print the average of the maximum value in each column of X_norm
print(X_norm.max(axis = 0).mean())

-3.1974423109204507e-18
-1.7312099310720992
1.7298585087349825


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [86]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([0, 1, 2, 3, 4])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [96]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])
print(row_indices)

[655 556 441 325 887 231 820 119 257 961 255  85 958 296 734 222 294 844
 606 883 927 951 259 299 566 375  88 438 884 396 544 413 502 581 487 759
 931 965 782 716 731 861 235 914 725 509 238 282 570 870  11 301 180 799
  77 159 464 836 504 684 292 324 786 310 804 991 133 541 741 772 765 244
 916   9 890   7 213 847 383 585 516 776 718  69 840 386 700 333 586 882
 641 410 411 595 963 945 484 680 179 543 561 922 520  35 949 362 843 492
 512 161 498  73 899 697 901  38 258 351 637 573 875 999 443 618 873 177
 609 175 592 677 651 750 335 218  93 385 346 323 997 791 913 910 427 649
 932 407 193 358 185 280 421 228 104 401 363 339 500 738 121 674 130 397
 646 533 885 548 819 852 778 227 357 962 477 474  81 691 937 792 611 139
 850 876  47 306 976  16 261 155 676 217 508 993 752 326  49 967 699 801
 476 886 102  14 983 514  18 281 493 764  43 633 195 797 124  56 826  22
 429 703 569 822 675 898 971 445 934 425 100 616  80 194 270 462 969 466
 707 933 625 475 755 770 334 182 810 713 108   4  5

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [125]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
sixty = int(len(X_norm)*0.6)
eighty = int(len(X_norm)*0.8)

# Create a Training Set
X_train = X_norm[row_indices[:sixty]]

# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[sixty:eighty]]

# Create a Test Set
X_test = X_norm[row_indices[eighty:]]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [126]:
# Print the shape of X_train
print(X_train[0])
print(X_norm[row_indices[0]])
print(X_train.shape)

# Print the shape of X_crossVal
print(X_crossVal[0])
print(X_norm[row_indices[600]])
print(X_crossVal.shape)

# Print the shape of X_test
print(X_test[0])
print(X_norm[row_indices[800]])
print(X_test.shape)

[-0.6485825  -0.70648797  0.47138314 -1.45600931 -1.36982666 -0.31519652
 -0.68595619  1.56731648 -1.01943931  1.38973574 -1.75674435 -1.27894258
 -0.47554628 -0.72417698  1.08598648 -0.3608413   0.91958945  1.16881273
  1.05905461 -1.29834938]
[-0.6485825  -0.70648797  0.47138314 -1.45600931 -1.36982666 -0.31519652
 -0.68595619  1.56731648 -1.01943931  1.38973574 -1.75674435 -1.27894258
 -0.47554628 -0.72417698  1.08598648 -0.3608413   0.91958945  1.16881273
  1.05905461 -1.29834938]
(600, 20)
[-0.95811155  0.78490896  1.65909389  1.12779652  0.20022971 -1.3064339
 -1.42318142  1.11348725  0.825981    1.65673889 -1.19036276  0.09994378
 -0.77343512 -0.76022562 -0.68795552 -0.3505171  -0.74558409  0.14202199
 -1.07662388 -0.61925219]
[-0.95811155  0.78490896  1.65909389  1.12779652  0.20022971 -1.3064339
 -1.42318142  1.11348725  0.825981    1.65673889 -1.19036276  0.09994378
 -0.77343512 -0.76022562 -0.68795552 -0.3505171  -0.74558409  0.14202199
 -1.07662388 -0.61925219]
(200, 20)
[-